# Pytorch深度学习框架简介

In [2]:
# 版本
import torch
print(torch.__version__)

1.11.0+cu113


## 张量的类型

In [16]:
import torch
# torch支持的数据类型
print(torch.float is torch.float32)
print(torch.double is torch.float64)
print(torch.half is torch.float16)
print(torch.short is torch.int16)
print(torch.int is torch.int32)
print(torch.long is torch.int64)
# 另外还支持
# torch.uint8 torch.int8 torch.bool
print("="*9)

True
True
True
True
True
True


## 张量创建

In [15]:
import numpy as np
import torch
from torch import tensor
# print(torch.tensor([1,2,3,4]))
print(torch.tensor([1,2,3,4]))
print(torch.tensor([1,2,3,4]).dtype)
print(torch.tensor([1,2,3,4]).type())
print("="*9)

# 从numpy创建
# torch的默认浮点是32位的，numpy是64位的
print(torch.tensor([1.0, 2.0, 3.0, 4.0]).dtype)
print(torch.tensor(np.array([1.0, 2.0, 3.0, 4.0])).dtype)
print("="*9)

# 类型转换
float_tensor = torch.tensor(np.arange(10), dtype=torch.float64)
print(float_tensor)
int_tensor = float_tensor.to(torch.int)
print(int_tensor)
print("="*9)

# 通过内置函数创建
print(torch.rand(3, 3)) # 均匀分布
print(torch.randn(3, 4, 5)) # 标准正态分布
print(torch.zeros(2, 3)) # 全0矩阵
print(torch.ones(2, 3)) # 全1矩阵
print(torch.eye(4)) # 单位矩阵
print(torch.randint(1, 10, (10, ))) # 随机整数

# 使用like系创建
base = torch.randn(3,4)
one_like = torch.ones_like(base)
zero_like = torch.zeros_like(base)
random_like = torch.rand_like(base)

tensor([1, 2, 3, 4])
torch.int64
torch.LongTensor
torch.float32
torch.float64
tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)
tensor([[0.1355, 0.1292, 0.1756],
        [0.6181, 0.2374, 0.5208],
        [0.9602, 0.5415, 0.4768]])
tensor([[[-1.0044, -0.5003,  0.4817,  1.0805,  0.2029],
         [ 1.6441, -0.2607, -1.0867,  1.1477,  0.3658],
         [ 1.4103, -0.6263, -0.5787, -1.0953, -1.6389],
         [-1.2681,  0.2339, -0.4071,  0.4023, -1.2800]],

        [[-1.0553,  0.9620,  0.0335, -0.7045, -0.0882],
         [-2.0618, -3.7923,  3.2679, -1.7934,  1.1875],
         [-0.5285, -1.0066,  1.8365,  0.1928,  0.9412],
         [-1.3469,  1.6225, -0.8181, -1.4446,  0.7415]],

        [[ 0.5228, -0.4694,  0.8319,  0.9243,  0.6221],
         [-0.7876, -1.7585, -1.3794, -0.4983, -1.4728],
         [ 0.2537,  1.5355, -0.6539,  0.4416,  0.0738],
         [-0.7016,  0.7648, -0.0900,  0.0943, -0.7359]]])
tensor([[0., 

## 张量的存储设备
只有都在cpu，或都在gpu的同一张卡上，张量之间才能互相运算，否则会报错。

In [14]:
tensor = torch.tensor(np.linspace(-1, 1, 100), dtype=torch.float, device="cpu")
print(tensor.device)
tensor = tensor.cuda(5)
print(tensor.device)
tensor = tensor.cpu()
print(tensor.device)
tensor = tensor.to("cuda:5")
print(tensor.device)
tensor = tensor.cpu()

cpu
cuda:5
cpu
cuda:5


## 张量维度相关的方法

In [30]:
t = torch.randn(2, 3, 4)
# 维度数量
print(t.ndim, t.ndimension())
# 元素总数
print(t.nelement())
# size与shape
print(t.size(), t.shape, t.size(-1))

# 重整shape, 可以使用.reshape方法，也可以使用view方法。
# reshape方法可以确保合法的重整必定成功，但view只有在满足兼容条件时才能成功？
# view必定不做拷贝，reshape也许会拷贝。
new_tensor = torch.ones(4, 4, dtype=torch.int)
another_tensor = new_tensor.reshape(2, 8)
print(another_tensor)
print(new_tensor.data_ptr(), another_tensor.data_ptr(), sep="\n")
new_tensor[2, 2]=0
print(new_tensor)
print(another_tensor)

3 3
24
torch.Size([2, 3, 4]) torch.Size([2, 3, 4]) 4
tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)
tensor([[1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1]], dtype=torch.int32)
93876346295232
93876346295232
tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 0, 1],
        [1, 1, 1, 1]], dtype=torch.int32)
tensor([[1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 0, 1, 1, 1, 1, 1]], dtype=torch.int32)


## 张量切片与方便的掩码

In [37]:
import torch

t = torch.randn(2, 3, 4)
print(t)
print(t[1, 2, 3], t[1][2][3])
print(t[:, 2, 3])
# 方便的掩码
print((t>0).to(torch.uint8))
print(t[t>0])



tensor([[[-0.7314,  0.3722, -0.4829, -1.3744],
         [ 1.0166,  1.1601, -0.9600,  0.2867],
         [ 0.4411,  0.9263,  0.7633,  1.0894]],

        [[ 1.8161, -0.5918, -1.3780, -0.8696],
         [-1.9779, -0.7498, -1.8901,  0.6590],
         [-1.2350, -1.2828, -2.5658, -0.9084]]])
tensor(-0.9084) tensor(-0.9084)
tensor([ 1.0894, -0.9084])
tensor([[[0, 1, 0, 0],
         [1, 1, 0, 1],
         [1, 1, 1, 1]],

        [[1, 0, 0, 0],
         [0, 0, 0, 1],
         [0, 0, 0, 0]]], dtype=torch.uint8)
tensor([0.3722, 1.0166, 1.1601, 0.2867, 0.4411, 0.9263, 0.7633, 1.0894, 1.8161,
        0.6590])


## 张量自运算

In [43]:
import torch
t = torch.rand(3,4)
print(t)
print(t.sqrt())
print(t.mean()) # 通过指定维度，可以求取特定维度的mean与sum等
print(t.sum())
print(t.argmax(0))
print(t.max(0))
print("="*9)
# 拷贝向量
nt = torch.zeros_like(t)
# 在torch中，带有_的方法是原地更改的，故不需要写nt=...
nt.copy_(t)
print(nt)

tensor([[0.1074, 0.0795, 0.2458, 0.9804],
        [0.6620, 0.0442, 0.5432, 0.4888],
        [0.9265, 0.6012, 0.3177, 0.2526]])
tensor([[0.3278, 0.2820, 0.4958, 0.9902],
        [0.8136, 0.2102, 0.7370, 0.6991],
        [0.9626, 0.7754, 0.5636, 0.5026]])
tensor(0.4374)
tensor(5.2493)
tensor([2, 2, 1, 0])
torch.return_types.max(
values=tensor([0.9265, 0.6012, 0.5432, 0.9804]),
indices=tensor([2, 2, 1, 0]))
tensor([[0.1074, 0.0795, 0.2458, 0.9804],
        [0.6620, 0.0442, 0.5432, 0.4888],
        [0.9265, 0.6012, 0.3177, 0.2526]])


## 张量间运算

In [48]:
import torch
t1 = torch.tensor(range(1, 10))
t2 = torch.tensor(range(10, 1, -1))

print(t1+t2)
print(t1.add(t2))
print(torch.add(t1, t2))
print(t1-t2, t1*t2, t1/t2)

tensor([11, 11, 11, 11, 11, 11, 11, 11, 11])
tensor([11, 11, 11, 11, 11, 11, 11, 11, 11])
tensor([11, 11, 11, 11, 11, 11, 11, 11, 11])
tensor([-9, -7, -5, -3, -1,  1,  3,  5,  7]) tensor([10, 18, 24, 28, 30, 30, 28, 24, 18]) tensor([0.1000, 0.2222, 0.3750, 0.5714, 0.8333, 1.2000, 1.7500, 2.6667, 4.5000])


## 矩阵乘法，批乘法与爱因斯坦求和约定

In [50]:
import torch
# 矩阵乘法
t1 = torch.randn(2, 3)
t2 = torch.randn(3, 4)
print(torch.mm(t1, t2), t1@t2)

print("="*9)
# 批乘法
t1 = torch.randn(3, 2, 3)
t2 = torch.randn(3, 3, 4)
# 两种写法是相同的，torch可以自己判断出是批乘法
print(torch.bmm(t1, t2), t1@t2)

# 爱因斯坦求和约定
print(torch.einsum("abc,acd->abd", t1, t2))

tensor([[-0.5754, -1.0357, -1.2547,  0.0307],
        [-0.7101, -0.6728,  0.8748,  2.8021]]) tensor([[-0.5754, -1.0357, -1.2547,  0.0307],
        [-0.7101, -0.6728,  0.8748,  2.8021]])
tensor([[[-0.9862,  2.0148, -0.0999, -0.1824],
         [-3.8542,  0.4459, -4.2813, -0.7014]],

        [[-1.3157, -0.8132, -1.7206, -2.4205],
         [ 0.0772, -1.0718,  1.1261,  0.9608]],

        [[-0.2986,  0.2007,  3.0160,  0.6551],
         [ 1.3310,  0.1772, -0.0059, -1.0315]]]) tensor([[[-0.9862,  2.0148, -0.0999, -0.1824],
         [-3.8542,  0.4459, -4.2813, -0.7014]],

        [[-1.3157, -0.8132, -1.7206, -2.4205],
         [ 0.0772, -1.0718,  1.1261,  0.9608]],

        [[-0.2986,  0.2007,  3.0160,  0.6551],
         [ 1.3310,  0.1772, -0.0059, -1.0315]]])
tensor([[[-0.9862,  2.0148, -0.0999, -0.1824],
         [-3.8542,  0.4459, -4.2813, -0.7014]],

        [[-1.3157, -0.8132, -1.7206, -2.4205],
         [ 0.0772, -1.0718,  1.1261,  0.9608]],

        [[-0.2986,  0.2007,  3.0160,  0.6551],

## 张量拼接与分割

In [58]:
import torch
t1 = torch.randn(3, 4)
t2 = torch.randn(3, 4)
t3 = torch.randn(3, 4)
t4 = torch.randn(3, 4)
# cat不会新增维度
print(torch.cat([t1, t2, t3, t4], -1).shape) # 这样，第一个维度是相同的，可以拼接，第二个维度会合并,得(3, 16)
# stack是新增维度的，dim决定了新增的维度放置在第几维
print(torch.stack([t1, t2, t3, t4], dim=0).shape)
# split告诉torch怎么分,这里将4维度分成1，2，1
print(t1.split([1, 2, 1], dim=-1))
# chunk告诉torch分成几个, 这里，把最后一个维度均分成2个。
print(t1.chunk(2, dim=-1))

torch.Size([3, 16])
torch.Size([4, 3, 4])
(tensor([[-1.4122],
        [ 0.9945],
        [ 0.0597]]), tensor([[-3.5429, -0.2772],
        [-1.0728,  0.8370],
        [-1.0781, -0.2682]]), tensor([[ 0.5112],
        [-1.5331],
        [ 0.2329]]))
(tensor([[-1.4122, -3.5429],
        [ 0.9945, -1.0728],
        [ 0.0597, -1.0781]]), tensor([[-0.2772,  0.5112],
        [ 0.8370, -1.5331],
        [-0.2682,  0.2329]]))


## 消除与增加1维度

In [61]:
import torch
# 增加为1的维度对任何张量都是可以的
t = torch.randn(3, 4)
print(t.shape)
t.unsqueeze_(1)
print(t.shape)

# 可以方便地消除为1的维度
print(t.squeeze().shape)

torch.Size([3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 4])


增加与消除维度对张量的广播是必要的。使得张量能与另一个张量之间达成维度的匹配，以便广播。

In [63]:
import torch
t1 = torch.randn(3, 4, 5)
t2 = torch.randn(3, 5)
# 要让t1+t2，直接这样做是不行的，故对t2升维
t2.unsqueeze_(1)
print(t2.shape)
# 这样，在进行t1+t2时，第一个维度会进行广播。
print(t1+t2)

torch.Size([3, 1, 5])
tensor([[[ 0.1089, -1.4662,  0.2281, -2.1201, -0.3451],
         [ 1.9122, -0.8835,  1.6466, -0.7086, -1.4303],
         [-0.0524,  0.1557, -0.3267, -0.6480, -1.1932],
         [-0.7810, -1.5105,  0.4413, -0.3786, -2.4496]],

        [[-0.4762,  2.1753, -3.6313, -0.4530,  1.4494],
         [ 0.7417,  0.8084, -2.0541, -1.7982, -1.1202],
         [ 1.4720,  1.9049, -1.7990, -2.3076,  1.0320],
         [-1.3049,  1.5306, -3.9112, -1.3204,  0.6329]],

        [[ 1.5535, -0.9278,  1.1954, -0.4431,  1.3355],
         [-0.4347, -1.4892,  0.5054,  0.0472,  1.5042],
         [-0.5629, -1.1739,  1.3661,  0.8342,  3.1323],
         [ 0.7827, -0.4685,  0.3974, -0.2244,  2.0698]]])


## TODO 2.7